module elementaryProcessor(	
		input	logic [31:0] 	DataIn	, // data input
		output	logic [31:0]	DataOut	, // data output
		input	logic [7:0]		Func	, // selects the function
		// Synchronisation signals
		input	logic 			Empty	, // data input is ready
		input	logic 			Full	, // data output must wait
		output	logic  			Read	, // get data input
		output	logic 			Write	, // send data output
		input	logic 			Init	, // run the function
		
		input	logic 			clock	);
	// From RALU to CROM
	logic       	crOut    	; // carry generated by ALU
	logic			eq			; // leftOperand == RightOperand
	logic			geq	        ; // leftOperand >= RightOperand
	logic			leq	        ; // leftOperand <= RightOperand
	logic			zero	    ; // leftOperand == 0
	logic			sgn	        ; // leftOperand[31] = signum
	logic			oddity	    ; // leftOperand[0] 
	// From CROM to RALU
	logic [4:0] 	leftAddr    ; // selects leftOperand
    logic [4:0] 	rightAddr  	; // selects RightOperand
	logic			crIn		; // carry aplied on ALU input
    logic [4:0] 	destAddr    ; // selects destination of result
	logic			load		; // selects DataIn as leftOperand
	logic			we			; // write result at destAddr
	logic [3:0] 	aluFunc     ; // selects ALU's function
							
	RALU epRALU(.leftOut	(DataOut	),  
				.crOut    	(crOut    	),
				.eq			(eq			),
				.geq		(geq		),
				.leq		(leq		),
				.zero		(zero		),
				.leftAddr   (leftAddr   ),
				.rightAddr  (rightAddr  ),
				.destAddr   (destAddr   ),
				.crIn		(crIn		),
				.in			(DataIn		),
				.load		(load		),
				.we			(we			),
				.aluFunc    (aluFunc    ),
				.clock  	(clock  	));
	CROM epCROM(.Func		(Func		),
				.eq			(eq			),
				.geq		(geq		),
				.leq		(leq		),
				.zero		(zero		),
				.sgn		(DataOut[31]),
				.oddity		(DataOut[0]	),
				.crOut    	(crOut		),
				.Empty		(Empty		),
				.Full		(Full		),
				.leftAddr   (leftAddr   ),
				.rightAddr  (rightAddr  ),
				.destAddr   (destAddr   ),
				.crIn		(crIn		),
				.load		(load		),
				.we			(we			),
				.aluFunc    (aluFunc    ),
				.Read		(Read		),
				.Write		(Write		),
				.Init		(Init		),
				.clock  	(clock		));
endmodule

