// Generated by CIRCT firtool-1.99.1
module SevenSegmentDisplay(	// src/main/scala/scabook/SevenSegmentDisplay.scala:8:7
  input        clock,	// src/main/scala/scabook/SevenSegmentDisplay.scala:8:7
               reset,	// src/main/scala/scabook/SevenSegmentDisplay.scala:8:7
  input  [3:0] io_binIn,	// src/main/scala/scabook/SevenSegmentDisplay.scala:9:14
  output [6:0] io_segOut	// src/main/scala/scabook/SevenSegmentDisplay.scala:9:14
);

  wire [15:0][6:0] _GEN =
    '{7'h0,
      7'h0,
      7'h0,
      7'h0,
      7'h0,
      7'h0,
      7'h7B,
      7'h7F,
      7'h70,
      7'h5F,
      7'h5B,
      7'h33,
      7'h79,
      7'h6D,
      7'h30,
      7'h7E};	// src/main/scala/scabook/SevenSegmentDisplay.scala:14:15, :16:{26,35,47}, :17:{26,35,47}, :18:{26,35,47}, :19:{26,35,47}, :20:{26,35,47}, :21:{26,35,47}, :22:{26,35,47}, :23:{26,35,47}, :24:{26,35,47}, :25:{26,35,47}
  assign io_segOut = _GEN[io_binIn];	// src/main/scala/scabook/SevenSegmentDisplay.scala:8:7, :14:15, :16:{26,35,47}, :17:{26,35,47}, :18:{26,35,47}, :19:{26,35,47}, :20:{26,35,47}, :21:{26,35,47}, :22:{26,35,47}, :23:{26,35,47}, :24:{26,35,47}, :25:{26,35,47}
endmodule

