// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module WaveFormGenerator(	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
  input  clock,	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
         reset,	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
  output io_randomWave,	// src/main/scala/scabook/WaveFormGenerator.scala:9:14
         io_clockWave	// src/main/scala/scabook/WaveFormGenerator.scala:9:14
);

  wire [7:0] _GEN = '{1'h0, 1'h0, 1'h0, 1'h0, 1'h1, 1'h0, 1'h1, 1'h0};	// src/main/scala/scabook/WaveFormGenerator.scala:17:17
  reg  [2:0] randomIndex;	// src/main/scala/scabook/WaveFormGenerator.scala:16:28
  reg        clockToggle;	// src/main/scala/scabook/WaveFormGenerator.scala:21:28
  always @(posedge clock) begin	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
    if (reset) begin	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
      randomIndex <= 3'h0;	// src/main/scala/scabook/WaveFormGenerator.scala:16:28
      clockToggle <= 1'h0;	// src/main/scala/scabook/WaveFormGenerator.scala:8:7, :21:28
    end
    else begin	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
      if (randomIndex == 3'h4)	// src/main/scala/scabook/WaveFormGenerator.scala:16:28, :18:34
        randomIndex <= 3'h0;	// src/main/scala/scabook/WaveFormGenerator.scala:16:28
      else	// src/main/scala/scabook/WaveFormGenerator.scala:18:34
        randomIndex <= randomIndex + 3'h1;	// src/main/scala/scabook/WaveFormGenerator.scala:16:28, :18:60
      clockToggle <= ~clockToggle;	// src/main/scala/scabook/WaveFormGenerator.scala:21:28, :22:18
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
        randomIndex = _RANDOM[/*Zero width*/ 1'b0][2:0];	// src/main/scala/scabook/WaveFormGenerator.scala:8:7, :16:28
        clockToggle = _RANDOM[/*Zero width*/ 1'b0][3];	// src/main/scala/scabook/WaveFormGenerator.scala:8:7, :16:28, :21:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scabook/WaveFormGenerator.scala:8:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_randomWave = _GEN[randomIndex];	// src/main/scala/scabook/WaveFormGenerator.scala:8:7, :16:28, :17:17
  assign io_clockWave = clockToggle;	// src/main/scala/scabook/WaveFormGenerator.scala:8:7, :21:28
endmodule

