// Generated by CIRCT firtool-1.62.0
module WaveFormGenerator(
  input  clock,
         reset,
  output io_randomWave,
         io_clockWave
);

  wire [7:0] _GEN = '{1'h0, 1'h0, 1'h0, 1'h0, 1'h1, 1'h0, 1'h1, 1'h0};
  reg  [2:0] randomIndex;
  reg        clockToggle;
  always @(posedge clock) begin
    if (reset) begin
      randomIndex <= 3'h0;
      clockToggle <= 1'h0;
    end
    else begin
      if (randomIndex == 3'h4)
        randomIndex <= 3'h0;
      else
        randomIndex <= randomIndex + 3'h1;
      clockToggle <= ~clockToggle;
    end
  end // always @(posedge)
  assign io_randomWave = _GEN[randomIndex];
  assign io_clockWave = clockToggle;
endmodule

